version: "2"
exclude_patterns:
- "config/"
- "**/node_modules/"
- "**/vendor/"
- "**/tests/"
- "**/__mocks__/"
- "**/__tests__/"
- "**/*.spec.php"
- "storage/*"
- "resources/*"
- "public/*"
- "tailwind.config.js"
- "webpack.dev.js"
- "webpack.production.js"
- "webpack.test.js"
