# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/php:7.3-stretch-node-browsers
    working_directory: ~/music
jobs:
  build_project:
    executor: my-executor
    steps:
      - checkout

      - run: sudo apt update && sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip

      # Download and cache dependencies

      # composer cache
      - restore_cache:
          keys:
          # "composer.lock" can be used if it is committed to the repo
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer update --no-interaction --no-progress --prefer-dist --optimize-autoloader --ignore-platform-reqs
      
   
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run: cp .env.testing .env
      - run: php artisan key:generate
      - run: php artisan config:cache

      # node cache

      - restore_cache:
          keys:
            - node-v4-{{ checksum "package.json" }}
            - node-v4-
      - run: npm install
      - save_cache:
          key: node-v4-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.yarn
      - persist_to_workspace:
          root: .
          paths: .
  lint:
    executor: my-executor
    steps:
      - attach_workspace:
          at: ~/music
      - run: composer lint
  
  test_and_report:
    executor: my-executor
    steps:
      - attach_workspace:
          at: ~/music
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run: 
          name: Run LMS_Music Tests
          command: |
            ./cc-test-reporter before-build
            ./vendor/bin/phpunit --coverage-clover clover.xml
            ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?
workflows:
  version: 2
  run_tests:
    jobs:
      - build_project
      - lint:
          requires:
            - build_project
      - test_and_report:
          requires:
            - build_project
